#!/bin/bash

function show_error_dialog {
    zenity --error --text "$1"
    exit 1
}

# Tomar una captura de pantalla de una porción seleccionada de la pantalla y guardarla como un archivo de imagen
gnome-screenshot -a -f /tmp/screenshot.png || show_error_dialog "Error: no se pudo tomar la captura de pantalla."

# Extraer texto de la imagen utilizando Tesseract
tesseract /tmp/screenshot.png /tmp/extracted_text || show_error_dialog "Error: no se pudo extraer texto de la imagen."

# Copiar el texto extraído al portapapeles
cat /tmp/extracted_text.txt | wl-copy || show_error_dialog "Error: no se pudo copiar el texto al portapapeles."

# Limpiar los archivos temporales
rm /tmp/screenshot.png || show_error_dialog "Error: no se pudo eliminar el archivo de captura de pantalla."
rm /tmp/extracted_text.txt || show_error_dialog "Error: no se pudo eliminar el archivo de texto extraído."

